# Project-wide Gradle settings.

# AndroidX wajib diaktifkan karena semua dependency proyek ini
# (Material, AppCompat, RecyclerView, dll) berbasis AndroidX.
android.useAndroidX=true
android.enableJetifier=false

# Opsi umum untuk mempercepat build.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true
